### ISSUE TITLE
Front-End

### ISSUE THREAD

**Issue by fidel-bello** [fidel-bello/epic-poggers-ecomstore#4]
- create navbar
- navbar should contain a search bar in the middle, logo on left, and login and cart in the right
- amazon would be a good resource to look at.. since the app is amazon mock but the navbar wouldn't be as intense
-  will have the logo in image files in the front end to use

**Comment by fidel-bello** [comment]
Good job fellas

**Comment by ivan-ngchakming** [comment]
This is not done either? We still need to fix all the styles and fill in the placeholder for each function?

**Comment by fidel-bello** [comment]
Yes this issue is done. Navbar was created and now we can work more off of it. More issues will be made to improve it

**Comment by nmp14** [comment]
👀 👀.

**Comment by fidel-bello** [comment]
Sup Nate, I'll be back on tomorrow for more issues. I'll take my pc to vacation to practice more on the issue making 😅

**Comment by nmp14** [comment]
Bro take the vacation. Don't make silly tickets on that. But if you wanna practice issue making, write user stories or acceptance criteria so if you assign an issue to Ivan or whatever, they know what it'll mean for the issue to be finished. Something like just saying 

AC
-------
- The navbar needs to be visually implemented With x, y, and z. Such as your logo, searchbar, etc. Only the styling should be implemented currently. The functionalities will be implemented later.
- Only the design for non-registered users should be implemented currently as authentication is WIP. So conditional rendering for authentication relevant areas will be handled in future tickets.

As a shitty example of a 'make a navbar' ticket. Normally in a company of my size, they have a UX/UI guy provide a visual mock up too and you have to code it to look exactly like that or you get hit with silly bug tickets that count against you. But that's beyond a small project like this with no UI designer. Just fun info of work life.

**Comment by fidel-bello** [comment]
yea, being descriptive is where I fail haha , need to work on it!
