### ISSUE TITLE
Bug in pagination and products

### ISSUE THREAD

**Issue by fidel-bello** [fidel-bello/epic-poggers-ecomstore#85]
- there is a bug in the pagination where only 8 products show. when there is 9

![image](https://user-images.githubusercontent.com/73322116/168735356-280a76cd-347c-43d9-a66d-4b9e7b85e90c.png)

![image](https://user-images.githubusercontent.com/73322116/168735529-179f8cfe-1b96-412a-b1e9-c70e1269a03d.png)

- should be 3 pages
-  could be an issue in the fetch
 ```typescript
//could be this 
<Pagination
          count={Math.ceil(data.productCount / data.count) - 1}
/>

//or this fetch
  const { data, isLoading } = useQuery<{
    count: number;
    productCount: number;
    products: Product[];
  }>(['get-products', page], () => axios.get(`${BASE_URL}/v1/products?page=${page}`).then((res) => res?.data));

// will look into this
```

**Comment by ivan-ngchakming** [comment]
My bad, should the round up in the pagination component prop

```
<Pagination
  count={Math.ceil(data.productCount / data.count) - 1}  // wrong
/>

<Pagination
  count={Math.ceil(data.productCount / data.count)}  // fixed
/>
```
